### ISSUE TITLE
%p produces capital AM/PM while %P produces lower am/pm

### ISSUE THREAD

**Issue by brozow** [rluiten/elm-date-extra#3]
%-d %b %Y %-H:%M:%S %p

produces a date with AM/PM but it should be am/pm

Similarly for %P but reversed

**Comment by rluiten** [comment]
If you are saying that upper lower case "p" as in "%p" should produce lower case "am/pm" but is producing the upper case "AM/PM" then this is the expected behavior and not a bug.

The lower case "p" should produce upper case "AM/PM" and vice versa as it was considered bad form to create our own mappings so the behavior of existing widely used date formatting was copied from the ruby implementation as per http://apidock.com/ruby/DateTime/strftime

If I have misunderstood this issue can you clarify the bug further ?
