### ISSUE TITLE
Add Year as possible value for the Period data type

### ISSUE THREAD

**Issue by MikkelStorgaard** [rluiten/elm-date-extra#57]

**Comment by rluiten** [comment]
Sorry for the delay responding to you.

Period is a fixed length of time. It is an elapsed time concept, which does not include the concept of Years Months or Daylight saving variations because they do not represent a fixed length of time they are human abstractions.

If you want to do math with Years use Duration.
http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest/Date-Extra-Duration
